apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-html
  name: app-html
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-html
  type: LoadBalancer
status:
  loadBalancer: {}