apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: mypv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /meubanco/