apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypv
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
